version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - npm install
      - npm run build

  post_build:
    commands:
      - aws s3 sync build/ s3://my-frontend-bucket-kushagra --delete
      - aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
          --paths "/*"
