version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - npm install
      - npm run build

  post_build:
    commands:
      - aws s3 sync build/ "s3://$S3_BUCKET" --delete
      - aws cloudfront create-invalidation \
          --distribution-id $CDN_ID \
          --paths "/*"
